// This file is autogenerated by SwarggerAutoApi.js
export default client => ({
  ApplyRecord: {
    // 获取个人交易记录列表
    GetItems (params) {
      return context.$axios.get('/api/v2/pay/ApplyRecord/GetItems', {
        params
      })
    },
    GetItemByApplyRecordId (params) {
      return context.$axios.get('/api/v2/pay/ApplyRecord/GetItemByApplyRecordId', {
        params
      })
    },
    // 用户提交充值申请, 平台类型
    AddRechargeByUs (params) {
      return context.$axios.get('/api/v2/pay/ApplyRecord/AddRechargeByUs', {
        params
      })
    },
    // 用户提交充值申请, 众币平台
    AddRechargeByOther (params) {
      return context.$axios.get('/api/v2/pay/ApplyRecord/AddRechargeByOther', {
        params
      })
    },
    AddWithDrawalRecord (params) {
      return context.$axios.get('/api/v2/pay/ApplyRecord/AddWithDrawalRecord', {
        params
      })
    },
  },
  Article: {
    // 查讯首页资讯
    GetItems (params) {
      return context.$axios.get('/api/v2/biz/Article/GetItems', {
        params
      })
    },
  },
  BalanceRecord: {
    // 账变明细查询
    GetBalanceRecordReport (params) {
      return context.$axios.get('/api/v2/pay/BalanceRecord/GetBalanceRecordReport', {
        params
      })
    },
    // 获取账变明细关联订单数据
    GetBalanceRecordDetail (params) {
      return context.$axios.get('/api/v2/pay/BalanceRecord/GetBalanceRecordDetail', {
        params
      })
    },
  },
  BankCard: {
    // 绑定银行卡
    Add (params) {
      return context.$axios.get('/api/v2/biz/BankCard/Add', {
        params
      })
    },
    // 设置当前银行卡为默认状态
    SetIsDefault (params) {
      return context.$axios.get('/api/v2/biz/BankCard/SetIsDefault', {
        params
      })
    },
    // 当前用户的所有银行卡
    GetItems (params) {
      return context.$axios.get('/api/v2/biz/BankCard/GetItems', {
        params
      })
    },
    // 删除指定的银行卡
    Delete (params) {
      return context.$axios.get('/api/v2/biz/BankCard/Delete', {
        params
      })
    },
  },
  Common: {
    // 文件上传
    Upload (params) {
      return context.$axios.post('/api/v2/biz/Common/Upload', {
        params
      })
    },
    // 获取当前系统界面配置信息：logo,轮播图，客服配置 等信息
    GetWebConfig (params) {
      return context.$axios.get('/api/v2/biz/Common/GetWebConfig', {
        params
      })
    },
    // 获取昨日获奖信息
    GetTomorrowWinningList (params) {
      return context.$axios.get('/api/v2/biz/Common/GetTomorrowWinningList', {
        params
      })
    },
    // 获取实时中奖信息
    GetRealTimeWinningList (params) {
      return context.$axios.get('/api/v2/biz/Common/GetRealTimeWinningList', {
        params
      })
    },
  },
  FeedBack: {
    // 反馈意见
    GetItems (params) {
      return context.$axios.get('/api/v2/biz/FeedBack/GetItems', {
        params
      })
    },
    // 添加一条反馈意见
    Add (params) {
      return context.$axios.post('/api/v2/biz/FeedBack/Add', {
        params
      })
    },
  },
  Game: {
    // 会员获取游戏列表
    GetOpenGames (params) {
      return context.$axios.get('/api/v2/game/Game/GetOpenGames', {
        params
      })
    },
    // 获取游戏当前期号、开封盘时间
    GetGameTimes (params) {
      return context.$axios.get('/api/v2/game/Game/GetGameTimes', {
        params
      })
    },
    // 获取游戏下注赔率
    GetBetOdds (params) {
      return context.$axios.get('/api/v2/game/Game/GetBetOdds', {
        params
      })
    },
    // 获取指定游戏时间段的开奖记录
    GetLotteries (params) {
      return context.$axios.get('/api/v2/game/Game/GetLotteries', {
        params
      })
    },
    // 查询最后一期开奖信息
    GetLotteryLastItem (params) {
      return context.$axios.get('/api/v2/game/Game/GetLotteryLastItem', {
        params
      })
    },
    // 游戏下注
    Bet (params) {
      return context.$axios.post('/api/v2/game/Game/Bet', {
        params
      })
    },
    // 获取游戏露珠
    GetSeriesRows (params) {
      return context.$axios.get('/api/v2/game/Game/GetSeriesRows', {
        params
      })
    },
    // 两面长龙
    GetRegularPatterns (params) {
      return context.$axios.get('/api/v2/game/Game/GetRegularPatterns', {
        params
      })
    },
    // 获取已结、未结订单
    GetGameSettledReport (params) {
      return context.$axios.get('/api/v2/game/Game/GetGameSettledReport', {
        params
      })
    },
    // 会员前端获取开奖记录
    GetDayLotteries (params) {
      return context.$axios.get('/api/v2/game/Game/GetDayLotteries', {
        params
      })
    },
    // 获取结果走势
    GetLotteryTrend (params) {
      return context.$axios.get('/api/v2/game/Game/GetLotteryTrend', {
        params
      })
    },
    // 撤销订单
    RevokeOrder (params) {
      return context.$axios.post('/api/v2/game/Game/RevokeOrder', {
        params
      })
    },
    // 获取单个游戏玩法、单注最低、单注最高、单期最高信息
    GetGameInfo (params) {
      return context.$axios.get('/api/v2/game/Game/GetGameInfo', {
        params
      })
    },
    // 获取游戏规则信息
    GetGameRule (params) {
      return context.$axios.get('/api/v2/game/Game/GetGameRule', {
        params
      })
    },
    // 获取当前生肖排序
    GetShengXiao (params) {
      return context.$axios.get('/api/v2/game/Game/GetShengXiao', {
        params
      })
    },
  },
  Message: {
    // 当前用户未读消息
    GetItems (params) {
      return context.$axios.get('/api/v2/sys/Message/GetItems', {
        params
      })
    },
    Readed (params) {
      return context.$axios.get('/api/v2/sys/Message/Readed', {
        params
      })
    },
  },
  Notice: {
    // 获取指定类型的所有公告
    GetItemsEnable (params) {
      return context.$axios.get('/api/v2/sys/Notice/GetItemsEnable', {
        params
      })
    },
  },
  Payee: {
    // 会员获取可用支付方式配置列表，特殊处理银行卡和众币支付时配置传空
    GetAll (params) {
      return context.$axios.get('/api/v2/pay/Payee/GetAll', {
        params
      })
    },
  },
  User: {
    // 用户登录
    Login (params) {
      return context.$axios.post('/api/v2/biz/User/Login', {
        params
      })
    },
    // 调试登录
    DebugLogin (params) {
      return context.$axios.post('/api/v2/biz/User/DebugLogin', {
        params
      })
    },
    // 退出登录
    Logout (params) {
      return context.$axios.get('/api/v2/biz/User/Logout', {
        params
      })
    },
    // 会员注册【所有参数必填】
    Register (params) {
      return context.$axios.post('/api/v2/biz/User/Register', {
        params
      })
    },
    // 获取当前登录用户个人信息: 邮箱，微信，QQ，电话(模糊化参数)
    GetUserInfo (params) {
      return context.$axios.get('/api/v2/biz/User/GetUserInfo', {
        params
      })
    },
    // 获取当前登录用户资金账户信息(包含今日输赢，未结算金额)
    GetUserFund (params) {
      return context.$axios.get('/api/v2/biz/User/GetUserFund', {
        params
      })
    },
    // 用户忘记密码,发送邮件验证码
    GetEmailValidCode (params) {
      return context.$axios.get('/api/v2/biz/User/GetEmailValidCode', {
        params
      })
    },
    // 用户通过邮件验证码修改登录密码    // {account 登录账号,emailCode 邮箱验证码,password 密码,authCode 授权码}
    ResetPwd (params) {
      return context.$axios.post('/api/v2/biz/User/ResetPwd', {
        params
      })
    },
    // 用户修改登录密码=> { "oldPassword":旧密码（使用MD5编码,"newPassword":新密码（使用MD5编码 }
    ModifyLoginPwd (params) {
      return context.$axios.post('/api/v2/biz/User/ModifyLoginPwd', {
        params
      })
    },
    // 用户修改资金安全密码=> { "oldPassword":旧密码（使用MD5编码,"newPassword":新密码（使用MD5编码 }
    ModifySafePwd (params) {
      return context.$axios.post('/api/v2/biz/User/ModifySafePwd', {
        params
      })
    },
    // 修改（邮箱，微信，QQ，电话）联系信息 {"email":"邮箱账号","weChat":"微信账号","qq":"qq号","phone":"电话号码"}
    ModifyInfo (params) {
      return context.$axios.post('/api/v2/biz/User/ModifyInfo', {
        params
      })
    },
    // 当前用户设置安全问题和答案
    SetSafeQuestion (params) {
      return context.$axios.post('/api/v2/biz/User/SetSafeQuestion', {
        params
      })
    },
    // 验证安全答案
    CheckSafeAnswers (params) {
      return context.$axios.get('/api/v2/biz/User/CheckSafeAnswers', {
        params
      })
    },
    // 用户绑定个人信息
    BindUserIfno (params) {
      return context.$axios.get('/api/v2/biz/User/BindUserIfno', {
        params
      })
    },
    CheckExist (params) {
      return context.$axios.get('/api/v2/biz/User/CheckExist', {
        params
      })
    },
  },
  UserReport: {
    // 会员端报表查询
    GetUserReport (params) {
      return context.$axios.get('/api/v2/biz/UserReport/GetUserReport', {
        params
      })
    },
  },
  ValidCode: {
    // 获取一个新的验证码，并发放未登录认证的token.用于校验验证码
    GetValidCode (params) {
      return context.$axios.get('/api/v2/biz/ValidCode/GetValidCode', {
        params
      })
    },
})